import type { Metadata } from "next";
import {  Outfit } from "next/font/google";
import "../globals.css";



const font =Outfit()

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const AuthLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="fr">
      <body
        className={`${font.className} antialiased`}
      >
        <div className="bg-zinc-200 min-h-screen flex flex-col items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  );
};

export default AuthLayout;
